In [8]:
!mkdir ml-zoomcamp\homework_1

# Q1. Pandas version

In [53]:
# Import the necessary libraries
import pandas as pd
import numpy as np

In [54]:
# Check the version of pandas
pd.__version__

'2.2.2'

In [55]:
# Import the dataset
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"
df = pd.read_csv(url)

# Display the first few rows of the DataFrame
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

# Q2. Records count

In [56]:
# Check the shape of the DataFrame to find the records
df.shape[0]

2160

# Q3. Laptop brands

In [57]:
# Find the number of unique values in the 'Brand' column
df.Brand.nunique()

27

# Q4. Missing values

In [58]:
# Check the number of missing values in each column
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

Two columns columns 'Storage type' and 'GPU' have missing values.

# Q5. Maximum final price

In [59]:
# Find the laptops of the 'Dell' brand and the maximum price
df[df['Brand'] == 'Dell']['Final Price'].max()

3936.0

# Q6. Median value of Screen

In [61]:
# Calculate the median of the 'Screen' column
median_before = df['Screen'].median()
median_before

15.6

In [62]:
# Find the most frequent value in the 'Screen' column
most_frequent_value = df['Screen'].mode()[0]
most_frequent_value

15.6

In [63]:
# Fill the missing values in the 'Screen' column with the most frequent value
df['Screen'].fillna(most_frequent_value)


0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [64]:
# Calculate the median of the 'Screen' column after filling the missing values
median_after = df['Screen'].median()
median_after

15.6

# Q7. Sum of weights

In [44]:
# Check the unique values in the 'Brand' column
df.Brand.unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [46]:
# Find the laptops of the 'Innjoo' brand
innjoo_laptops = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]
innjoo_laptops

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [47]:
# Convert the DataFrame to a NumPy array
X = innjoo_laptops.values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [48]:
# Calculate the covariance matrix
XTX = X.T @ X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [49]:
# Calculate the inverse of the covariance matrix
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [50]:
# Create an array y
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [51]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y
w = XTX_inv @ X.T @ y
w

array([45.58076606,  0.42783519, 45.29127938])

In [52]:
# Calculate the sum of all elements in w
sum_w = round(w.sum(),2)
print(f"Sum of all elements in w: {sum_w}")

Sum of all elements in w: 91.3
